[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
board_microros_distro = humble
board_microros_transport = serial
upload_speed = 115200
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    waspinator/AccelStepper @ ^1.64
    gin66/FastAccelStepper @ ^0.30.6
; ไม่ต้องใส่ build_flags เรื่อง USB_CDC เหมือน S3